### ISSUE TITLE
SWRLRuleEngineAPI status?

### ISSUE THREAD

**Issue by jkyberneees** [protegeproject/swrlapi#8] opened 2015-08-07 12:59 UTC
Hi [Developer], trying to integrate the SWRLRuleEngineAPI by following your wiki tutorials (with some API changes), I can successfully create the rules, but those are not being executed by the SQWRLQueryEngine. 
Can you please advise me here? 

The code: 
```java
SQWRLQueryEngine engine...
SWRLAPIRule lRule = engine.createSWRLRule("R1", "Person(?p) ^ hasAge(?p, ?age)^ swrlb:greaterThan(?age, 17) -> Adult(?p)");
engine.infer();
```
Query code:
* Adult(?c)->sqwrl:select(?c)

The execution returns an empty set, while I expect a new re-classified individual. Am I correct?

Thanks in Advance,
Rolando SM

**Comment by martinjoconnor** [comment] 2015-08-07 22:51
This pretty basic query should work. However, I would need to see the ontology to see if it has the appropriate asserted axioms to make the required deduction.

Can you post it here.

Martin

**Comment by jkyberneees** [comment] 2015-08-08 11:36
Hi Martin, sorry for being so insistent ;)
Here is the ontology:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns="http://jwebsocket.org/ontologies/Person#"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:xml="http://www.w3.org/XML/1998/namespace"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:swrla="http://swrl.stanford.edu/ontologies/3.3/swrla.owl#"
	xmlns:person="http://jwebsocket.org/ontologies/Person#">

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>
</rdf:Description>

<!--  -->
<!--  -->
<!--  -->
<!-- ################################################################# -->
<!-- # -->
<!-- #    Data properties -->
<!-- # -->
<!-- ################################################################# -->
<!--  -->
<!--  -->
<!-- http://jwebsocket.org/ontologies/Person#hasAge -->

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person#hasAge">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#DatatypeProperty"/>
</rdf:Description>
<!--  -->
<!--  -->
<!--  -->
<!-- ################################################################# -->
<!-- # -->
<!-- #    Classes -->
<!-- # -->
<!-- ################################################################# -->
<!-- http://jwebsocket.org/ontologies/Person#Adult -->

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person#Adult">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
</rdf:Description>
<!--  -->
<!-- http://jwebsocket.org/ontologies/Person#Person -->

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person#Person">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
</rdf:Description>
<!--  -->
<!--  -->
<!--  -->
<!-- ################################################################# -->
<!-- # -->
<!-- #    Individuals -->
<!-- # -->
<!-- ################################################################# -->
<!--  -->
<!--  -->
<!-- http://jwebsocket.org/ontologies/Person#RolandoSM -->

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person#RolandoSM">
	<rdf:type rdf:resource="http://jwebsocket.org/ontologies/Person#Person"/>
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#NamedIndividual"/>
	<hasAge rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">29</hasAge>
</rdf:Description>

<!-- Generated by the OWL API (version 4.1.0) http://owlapi.sourceforge.net -->

</rdf:RDF>
```

Also there is another issue, when I create a rule like: "Person(?p) ^ hasAge(?p, ?age)^ swrlb:greaterThan(?age, 17) -> Adult(?p)", and I save it as a normal axiom into an ontology. Then when I reload that ontology I am not able anymore to query the ontology with SQWRL. HermiT supports just some basic rules meanwhile (a shame), but the SQWRLQueryEngine for some reason fail after reload.

* Test query: Person(?c)->sqwrl:select(?c)
* Exception after reload: org.swrlapi.parser.SWRLParseException: Invalid SWRL atom predicate 'Person'"

> NOTE: I don't save the inference in the ontology, just the SWRLRule axiom.

This is the new content(rule) that has been added to the ontology:
```xml
<!--  -->
<!--  -->
<!--  -->
<!-- ################################################################# -->
<!-- # -->
<!-- #    Rules -->
<!-- # -->
<!-- ################################################################# -->
<!--  -->
<!--  -->

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person#p">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#Variable"/>
</rdf:Description>

<rdf:Description rdf:about="http://jwebsocket.org/ontologies/Person#age">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#Variable"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid1">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#Imp"/>
	<body xmlns="http://www.w3.org/2003/11/swrl#" rdf:nodeID="genid8"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid8">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#AtomList"/>
	<rdf:first rdf:nodeID="genid9"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid9">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#ClassAtom"/>
	<argument1 xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#p"/>
	<classPredicate xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#Person"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid8">
	<rdf:rest rdf:nodeID="genid6"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid6">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#AtomList"/>
	<rdf:first rdf:nodeID="genid7"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid7">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#DatavaluedPropertyAtom"/>
	<argument1 xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#p"/>
	<argument2 xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#age"/>
	<propertyPredicate xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#hasAge"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid6">
	<rdf:rest rdf:nodeID="genid2"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid2">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#AtomList"/>
	<rdf:first rdf:nodeID="genid3"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid3">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#BuiltinAtom"/>
	<arguments xmlns="http://www.w3.org/2003/11/swrl#" rdf:nodeID="genid5"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid5">
	<rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#List"/>
	<rdf:first rdf:resource="http://jwebsocket.org/ontologies/Person#age"/>
	<rdf:rest rdf:nodeID="genid4"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid4">
	<rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#List"/>
	<rdf:first rdf:datatype="http://www.w3.org/2001/XMLSchema#int">17</rdf:first>
	<rdf:rest rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid3">
	<builtin xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://www.w3.org/2003/11/swrlb#greaterThan"/>
</rdf:Description>

<rdf:Description rdf:about="http://www.w3.org/2003/11/swrlb#greaterThan">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#Builtin"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid2">
	<rdf:rest rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid1">
	<head xmlns="http://www.w3.org/2003/11/swrl#" rdf:nodeID="genid10"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid10">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#AtomList"/>
	<rdf:first rdf:nodeID="genid11"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid11">
	<rdf:type rdf:resource="http://www.w3.org/2003/11/swrl#ClassAtom"/>
	<argument1 xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#p"/>
	<classPredicate xmlns="http://www.w3.org/2003/11/swrl#" rdf:resource="http://jwebsocket.org/ontologies/Person#Adult"/>
</rdf:Description>

<rdf:Description rdf:nodeID="genid10">
	<rdf:rest rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"/>
</rdf:Description>
```

**Comment by martinjoconnor** [comment] 2015-08-08 23:28
In the first ontology, you are using the xsd:integer type rather than the more common xsd:int. An unqualified numeric literal will default to xsd:int in the SWRL parser in the SWRLAPI - so the xsd:integer will be ignored because the types do not match. 

See:
http://stackoverflow.com/questions/15336872/xsd-what-is-the-difference-between-xsinteger-and-xsint

Sorry - can you separate new issues into separate threads. I can't really follow the second issue above.

**Comment by jkyberneees** [comment] 2015-08-09 15:28
Hi martin, thanks for your quick support. 
I already edited the issue description on top, I removed the second part because that was produced for an invalid serialization (not related to the SWRLAPI but the OWLAPI).
Meanwhile I can manage SWRL rules in OWL2 documents (VERY NICE), but NO success on executing those rules with the SQWRLQueryEngine. 
Today I synced the source code again, followed your hints for the types, and no result.

Can I use the Protege developer mail list to contact other SWRLAPI users? In order to not post inadequate content here. 

Best Regards,
Rolando

**Comment by martinjoconnor** [comment] 2015-08-09 21:15
Thanks for spotting this. This was a regression - and was not covered by my tests. It is now fixed.

I have some initial API-level tests here:

https://github.com/protegeproject/swrlapi-integration-tests/blob/master/src/test/java/org/swrlapi/PublicAPIIT.java

Try again after pulling the various components listed here:

https://github.com/protegeproject/swrltab-project

The developer list is probably the best place to post to get the most eyes on a problem.

**Closed** 2015-08-11 19:46 UTC
